name: Issue Report
description: "Create a report to help us improve."
body:
  - type:  checkboxes
    id: terms
    attributes:
      label: Welcome
      options:
        - label: Yes, I'm using the latest major release. Only such installations are supported.
          required: false
        - label: Yes, I'm using the supported system. Only such systems are supported.
          required: false
        - label: Yes, I have read all WIKI document,nothing can help me in my problem.
          required: false
        - label: Yes, I've searched similar issues on GitHub and didn't find any.
          required: false
        - label: Yes, I've included all information below (version, config, log, etc).
          required: false

  - type: textarea
    id: problem
    attributes:
      label: Description of the problem,screencshot would be good 
      placeholder: Telegram Bot timeout would prevent you from login to panel
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Version of x-ui
      value: |-
        <details>

        ```console
        $ x-ui version
        # 0.3.2
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: x-ui log or xray log
      value: |-
        <details>

        ```console
        # get tgbot error: Post "https://api.telegram.org/bot/getMe": dial tcp 10.10.34.36:443: i/o timeout
        ```

        </details>
    validations:
      required: true
